sudo: required
services: 
  - docker

script:
  - docker build -t harym/node .
  - docker images harym/node

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD


deploy:
  provider: script
  script: docker push harym/node
  on:
    branch : master