sudo: required
services: 
  - docker

script:
  - docker build -t harym/node .
  - docker images harym/node

before_deploy:
  - docker login -u harym -p Basile123


deploy:
  provider: script
  script: docker push harym/node
  on:
    branch : master